#@ load("@ytt:data", "data")
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: dev
secrets:
  - name: kpack-registry-credentials
imagePullSecrets:
  - name: kpack-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java
    - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default
  namespace: default
spec:
  serviceAccountRef:
    name: kpack-service-account
    namespace: dev
  tag: #@ data.values.tag
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs