apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions
subjects:
- kind: ServiceAccount
  namespace: dev
  name: github-actions
roleRef:
  kind: ClusterRole
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: dev
subjects:
- kind: ServiceAccount
  namespace: dev
  name: github-actions
roleRef:
  kind: Role
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions
rules:
- apiGroups: ['kpack.io']
  resources:
  - clusterbuilders
  verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: dev
rules:
- apiGroups: ['']
  resources: ['pods', 'pods/log']
  verbs: ['get', 'watch', 'list']
- apiGroups: ['kpack.io']
  resources:
  - builds
  verbs: ['get', 'watch', 'list', 'create']
