on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        id: build
        uses: ./
        with:
          # auth
          repository: https://github.com/spring-projects/spring-petclinic
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: ${{ secrets.NAMESPACE }}
          # image config
          destination: gcr.io/kontinue/emj/app-action
          serviceAccountName: kpack-service-account
          env: |
            BP_JAVA_VERSION=17

      - name: Validate Output
        run: |
          if [ "${{ steps.build.outputs.name }}" == "" ]; then
            echo "::error::No output from previous step"
            exit 1
          fi
